### ISSUE TITLE
Can you give the label map code sample in "Converting from csv to record" section?

### ISSUE THREAD

**Issue by umplane** [sglvladi/TensorFlowObjectDetectionTutorial#1]
http://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#converting-from-csv-to-record

In "Converting from csv to record" section. How to replace the label map code? Can you give the example of the code? Thank you.

**Comment by umplane** [comment]
and you miss to define 'img_path' flags too.

**Comment by sglvladi** [comment]
@umplane Apologies for the late response. 

Unfortunately the code in the specific file has not been written by me. I got it as is from a Youtube tutorial (see [here](https://youtu.be/K_mFnvzyLvc?t=9m13s)), which I have also referenced a couple of times within my tutorial. By the looks of it this is a generic piece of code that many people use, but all say that the label map code is not available, yet. 

However, I think that this could be implemented by reading the `label_map.pbtxt` file and using a dictionary to store a map between the `id` and `name` fields, where the `name` would be used as the `key` and `id` as the value, e.g.:
* Assume you have the following  `label_map.pbtxt` file:
``` 
item {
    id: 1
    name: 'cat'
}

item {
    id: 2
    name: 'dog'
}
```
* Then the desired label map dict would look like this:
``` python
label_map = {'cat' : 1, 'dog' : 2}  
```
* And you could then replace the `class_text_to_int1()` function with the following code:

``` python
 # TO-DO replace this with label map
def class_text_to_int(row_label):
    return label_map[row_label]
```

Hope this helps!

**Comment by umplane** [comment]
Thank you for your reply. You are very nice guy and i will keep learning in
Tensorflow / Machine Learning. 🙂


Best Regards,
Plane Smith
