### ISSUE TITLE
The dataset does not implement the AsGraphDefInternal() method needed to apply optimizations

### ISSUE THREAD

**Issue by pepis10** [sglvladi/TensorFlowObjectDetectionTutorial#102]
Hi, 

firstly I would like to thank you for the great documentation.   I went step by step through your documentation and I installed all necessary libraries and frameworks.    Everything went well, but in when I want to start a training process I get message: 
Instructions for updating:
Use `tf.cast` instead.
_2021-11-18 13:58:28.869017: W tensorflow/core/framework/dataset.cc:744] Input of GeneratorDatasetOp::Dataset will not be 
optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations._
I was googling a lot but withou succes....  please  can you point me to what I'm doing wrong?
Thanks....
Tomas

**Comment by sglvladi** [comment]
Hi Thomas,

Unfortunately, I can't be of much help. I have never come across this issue. I will leave this issue open in case someone else can provide an answer.

**Comment by Dex247** [comment]
Did you find a solution to it now? I am currently having the same issue

**Comment by Dex247** [comment]
> 

d you find a solution to it now? I am currently having the same issue

**Comment by Yozor4** [comment]
Did you find a solution to it now? I am currently having the same issue

**Comment by Dex247** [comment]
Yes. I swapped the machine I was using for a GPU machine. Get CUDA and
CUDNN well installed. That fixed my problem. You need a good and a high
spec. machine for training and optimization.
