### ISSUE TITLE
cannot import name 'anchor_generator_pb2' from 'object_detection.protos' on osx

### ISSUE THREAD

**Issue by dahang** [sglvladi/TensorFlowObjectDetectionTutorial#105]
for after Install testing 
need run  protoc object_detection/protos/*.proto --python_out=. 
and pip3.9 install .
before run python3.9 object_detection/builders/model_builder_tf2_test.py

**Comment by sglvladi** [comment]
@dahang This step is in the tutorial; please see [here](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#protobuf-installation-compilation)
