### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by turowicz** [sglvladi/TensorFlowObjectDetectionTutorial#11]
Hey @sglvladi first of all I'd like to thank you for this amazing tutorial that surely has taken a lot of work.

Have you considering adding the step about data augmentation and how to do it easily in TensorFlow?

Example:

https://medium.com/nanonets/how-to-use-deep-learning-when-you-have-limited-data-part-2-data-augmentation-c26971dc8ced

**Comment by sglvladi** [comment]
Hi @turowicz,

Thanks for the kind words! I am glad that this tutorial is proving to be useful.

I do like your idea of adding instructions for data augmentation. I guess I never really considered this as I didn't need it for my application, but it would certainly be nice to have.

Unfortunately I am currently in the last few month of my PhD and time is quite pressing. However, how would you feel about contributing to the tutorial by adding the section yourself? You can do this by forking this repo, making any changes on your fork and then submitting a pull request.

I could see this fitting under a new subsection called "Data Augmentation (Optional)" just after "Preparing workspace" in section "Training Custom Object Detector".  

Let me know what you think.

Cheers

**Comment by turowicz** [comment]
@sglvladi I will let you know when I have anything with augmentation that actually works. I'm happy to contribute.

**Comment by akashdeepjassal** [comment]
@turowicz 
In config file for your pipeline add values for data_augmenatation_options.
```
train_config: {
  batch_size: 1
  ...
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
}
```

The possible options for data augmentation are 
```
NormalizeImage normalize_image = 1;
RandomHorizontalFlip random_horizontal_flip = 2;
RandomPixelValueScale random_pixel_value_scale = 3;
RandomImageScale random_image_scale = 4;
RandomRGBtoGray random_rgb_to_gray = 5;
RandomAdjustBrightness random_adjust_brightness = 6;
RandomAdjustContrast random_adjust_contrast = 7;
RandomAdjustHue random_adjust_hue = 8;
RandomAdjustSaturation random_adjust_saturation = 9;
RandomDistortColor random_distort_color = 10;
RandomJitterBoxes random_jitter_boxes = 11;
RandomCropImage random_crop_image = 12;
RandomPadImage random_pad_image = 13;
RandomCropPadImage random_crop_pad_image = 14;
RandomCropToAspectRatio random_crop_to_aspect_ratio = 15;
RandomBlackPatches random_black_patches = 16;
RandomResizeMethod random_resize_method = 17;
ScaleBoxesToPixelCoordinates scale_boxes_to_pixel_coordinates = 18;
ResizeImage resize_image = 19;
SubtractChannelMean subtract_channel_mean = 20;
SSDRandomCrop ssd_random_crop = 21;
SSDRandomCropPad ssd_random_crop_pad = 22;
SSDRandomCropFixedAspectRatio ssd_random_crop_fixed_aspect_ratio = 23;
```

Change values for experimentation.

**Comment by turowicz** [comment]
@akashdeepjassal yesssssss thank you!
