### ISSUE TITLE
Getting Mutiple boxes before object detection

### ISSUE THREAD

**Issue by Rajasri21** [sglvladi/TensorFlowObjectDetectionTutorial#12]
Hi,
we are getting mutiple boxes while our code is running.we cant able to detect our object:
please find the below screenshot:
OS: windows 10
Tensorflow version:1.3.1
model:ssd_inspection_cococ
Python:3.6
![screenshot](https://user-images.githubusercontent.com/43840670/57367125-07bf5400-71a6-11e9-939c-e6aa4d550856.PNG)

could you please help on the above issue.

Regards
Rajasri

**Comment by AKIvan** [comment]
is there a way to draw circle instead of rectangular? the detection_graph or boxes to be represent with green circle ?

**Comment by sglvladi** [comment]
@Rajasri21 

Apologies. Although this repository contains a tutorial to assist you in installing and running some basic examples in Tensorflow, it is not intended as a discussion forum. Thus, I would suggest that you post any technical queries you have on StackOverflow, as advised by [Tensorflow](https://www.tensorflow.org/community/) themselves.

As a small note, I would like to comment that from the attached screenshot, I cannot make out the multiple boxes you are referring to. However, it is generally normal to receive multiple (overlapping) boxes. If and when you get multiple boxes, maybe you can select only the one with the highest score?

**Comment by sglvladi** [comment]
@Rajasri21 Closing the issue due to long inactivity. Feel free to re-open if necessary.
