### ISSUE TITLE
tensorflow object detection api on windows with gtx 1650 , cuda 10.0, cudnn 7.4

### ISSUE THREAD

**Issue by adouwitti** [sglvladi/TensorFlowObjectDetectionTutorial#17]
hi @sglvladi
 i hope that you are doing well. is it possible to install tensorflow object detection API on windows using NVIDIA GEFORCE GTX 1650, CUDA 10.0? i saw in tensorflow documentation that the version of cuda and cudnn used are 9.0 and 7.0 respectively. i am wondering, if it is possible to install using cuda 10.0. because, cuda 9.0 is not compatible with the driver installed on my computer.

**Comment by sglvladi** [comment]
Hi @adouwitti,

I am afraid I cannot provide you with a solid answer. I am confident that most of the instructions that are given in the tutorial should be valid for CUDA 10.0 and CUDNN 7.4, although the version of Tensorflow may need to be changed.

Unfortunately I don't currently have any spare time until September, so I won't be able to test things until then. 

If you manage to get it working, or have any more specific issues, feel free to come back and I will happily try to assist you.
