### ISSUE TITLE
not detecting the objects

### ISSUE THREAD

**Issue by harichandu13** [sglvladi/TensorFlowObjectDetectionTutorial#19]
I just followed the below links for object detection
1) https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html
2) https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html
3) https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/camera.html

All the steps were done perfectly without any errors, But i am unable to detect my required object.
Please let me know the reason for it.

**Comment by samudralaz** [comment]
Even i am facing the same problem, can anyone help me out from this issue.
Thanks in advance.

**Comment by sglvladi** [comment]
Hi @harichandu13,

Can you please be a little more specific? 

Are you getting any errors when you run the webcam script? If not, what is it you are trying to detect?

**Comment by harichandu13** [comment]
hi @sglvladi 
I am not getting any errors when running the webcam script, The webcam is opening but the object is not getting detected. 
I am trying to detect an object EGG.
for that i have trained my model with the egg images and labeled them.

**Comment by sglvladi** [comment]
Ok, and I am guessing you have followed the instructions for [exporting the graph](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#exporting-a-trained-inference-graph) and changed the relevant parts of the webcam script such that your new graph is imported?

**Comment by harichandu13** [comment]
Yes, that is the method I have used.
But I have a small doubt in it. Once exporting the graph we have to copy the frozen_inference_graph from the output_inference_graph folder to the training demo folder Am I Right @sglvladi
