### ISSUE TITLE
Changes needed to Converting *.xml to *.csv

### ISSUE THREAD

**Issue by jatansharma** [sglvladi/TensorFlowObjectDetectionTutorial#2]
Following changes I had to make in "generate_tfrecord.py" file to make it work with the given cmd command:

1. Define flag for image path which is passed through command line
`flags.DEFINE_string('img_path', '', 'Path to the images')`

2. Inside _create_tf_example_ definition change path to _FLAGS.img_path_
`with tf.gfile.GFile(os.path.join(FLAGS.img_path, '{}'.format(group.filename)), 'rb') as fid:`

Also, I got Nonetype error: _None has type NoneType, but expected one of: int, long_.  To fix this change the else return to 0 instead of null
`
def class_text_to_int(row_label):

    if row_label == FLAGS.label:  # 'ship':

        return 1

    else:

        return 0
`

PS: let me know if there is a better solution
PPS: Still waiting on label map implementation

**Comment by sglvladi** [comment]
Closing as there has been no correspondence in 3 months. Feel free to re-open if necessary.
