### ISSUE TITLE
Issue with this command "conda create -n labelImg pyqt=4"

### ISSUE THREAD

**Issue by jSquaredSolutions** [sglvladi/TensorFlowObjectDetectionTutorial#24]
When I run this command "conda create -n labelImg pyqt=4" I get:

```
PackagesNotFoundError: The following packages are not available from current channels:
  - pyqt=4

```

**Comment by sglvladi** [comment]
LabeImg seems to support PyQt5 now. Therefore there is no need to create a new conda environment.

Simply activate the environment you use for tensorflow, e.g. ``conda activate tf_gpu`` and run ``pip install labelImg``

**Comment by sglvladi** [comment]
Please check the updated version [here](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#labelimg-installation)
