### ISSUE TITLE
Tutorial now broken for Tensorflow 2.0

### ISSUE THREAD

**Issue by cayorodriguez** [sglvladi/TensorFlowObjectDetectionTutorial#25]

**Comment by cayorodriguez** [comment]
Seems that changes to the API now made the tutorial not followable with the new TF version. Scripts, for example, use Sessions and app, which have been deprecated. Is it possible to update them?

**Comment by sglvladi** [comment]
@cayorodriguez Thanks for the input. I am aware of the issues, which is why each version of the tutorial makes an explicit reference to the versions of the various components.

I would like to release a version for Tensorflow 2.0, however so far I have been unable to get object detection to work with the new version.

Have you managed to get TF 2.0 to run object detection?

**Comment by cayorodriguez** [comment]
Hi,

I have not. Haven't tried much. Just downgraded to previous versions.
==============
Carlos Rodriguez
==============

**Comment by yev-d** [comment]
Same here. 
Using Tensorflow2 everything was fine up to the step **Converting from *.csv to *.record**, where this error came up:
AttributeError: module 'tensorflow' has no attribute 'app'

**Comment by IamSierraCharlie** [comment]
As of the weekend just gone, I have used this documentation to train on a custom dataset using inception model.  I had to make some changes to get it to work - a few downgrades of modules such as numpy / matplotlib. Given the move to Tensorflow2 and that fact that there are many functions which are deprecated in TF2 (which were available in TF1) are there plans to update this documentation for use with TF2 or sunset?   It seems that as modules are updated, this document is getting harder to follow.  I guess I'm just looking to find out what the plan is moving forward.  Reading between the lines, I'm not sure TF1 will be well supported for much longer

**Comment by sglvladi** [comment]
@IamSierraCharlie I am surprised you've had to downgrade. Could you please open a new issue specifying the reasons that you had to do so? That would be very helpful. I suspect you must have received some errors for this to be necessary.

In terms of TF2. As outlined in the start of the tutorial, to the best of my knowledge, [TF2 does not yet fully support the object detection API](https://github.com/tensorflow/models/issues/6423#issuecomment-600925072). Last time I tried, I was able to use an already trained model to perform detection, but was unable to perform training. As this tutorial is intended as a full guide to setting up for both, I will delay a TF2 version until the api is fully supported.

**Comment by IamSierraCharlie** [comment]
Thanks for the info.  Yeah, there were errors.  Mainly with Numpy and Matplotlib - I overcame them with little trouble (just downgraded) but I will go through the process again in a few days.  I'll reference the tutorial to ensure that I'm following it properly.  If I see the errors again I'll raise a new issue - thanks

**Comment by sourangshupal** [comment]
Thanks for the update. Waiting for the training scripts to be updated.
