### ISSUE TITLE
tensorflow object detection api (ssd + mobilenet) for ocr (detection and reading). Bad for long symbol sequences

### ISSUE THREAD

**Issue by lenkele** [sglvladi/TensorFlowObjectDetectionTutorial#33]
I am trying to learn tensorflow object detection api (ssd + mobilenet architecture) on the example of reading sequences of Arabic numbers. 
Generated images with random sequences of numbers of different lengths - from one digit to 20 were fed to the input. 
The result is perfect detection and reading for short sequences (up to 5 characters). And a terrible result for long sequences - characters are skipped or several digits are read as one. 
What could be the problem? 
You can think about some kind of built-in preprocessing, but at the training stage, the network also saw sequences of different lengths. Many thanks!

**Comment by sglvladi** [comment]
@lenkele apologies. I cannot provide answers to your question. It seems like a question better posed in StackOverflow, where there will be plenty of people that can pick it up.
