### ISSUE TITLE
Error:  "from official.vision.image_classification.efficientnet import efficientnet_model ModuleNotFoundError: No module named 'official'"

### ISSUE THREAD

**Issue by sabeeha1** [sglvladi/TensorFlowObjectDetectionTutorial#43]
Using window OS and anaconda 64 bits python, All installed successfully but got error finally at running model_builder_tf2_test.py, set up PYTHONPATH for models directory in the environment settings but of no use.

**Comment by shahzaib3311** [comment]
@sabeeha1  found any solution? I'm having the same issue.
