### ISSUE TITLE
Readthedocs.io is not updated with the new version

### ISSUE THREAD

**Issue by aklingam7** [sglvladi/TensorFlowObjectDetectionTutorial#45]
The [website](http://tensorflow-object-detection-api-tutorial.readthedocs.io/) is still on the 1.14.2 version. It's been a month and a half, so I just wanted to bring it to your attention.

**Comment by sglvladi** [comment]
@aklingam7 Readthedocs' ``latest`` version has been set up to compile the latest commit of the ``master`` branch. 

Using the link you have provided above works fine for me. Try clearing your browser's cache and/or try the above link in a browser you haven't previously used to visit the tutorial.

**Comment by aklingam7** [comment]
Really sorry, I got confused because I spotted some deferences between the index.html in the latest release and the [webpage](http://tensorflow-object-detection-api-tutorial.readthedocs.io/). I thought the website was behind because I didn't see the 2.2 number anywhere, just the 1.14 and latest (which I thought meant the latest release). I guess it's the other way around.
