### ISSUE TITLE
Stoping and restarting training script starts from scratch

### ISSUE THREAD

**Issue by turowicz** [sglvladi/TensorFlowObjectDetectionTutorial#49]
Hey,

I'm having some serious issues each time I stop the training after a checkpoint has been created and run evaluation.

![image](https://user-images.githubusercontent.com/1055391/92927274-a5cbca00-f43d-11ea-84f1-ad19f5d04ecb.png)

It seems like the restarted job picks up the checkpoint step number but starts learning from scratch.

Cheers

**Comment by sglvladi** [comment]
@turowicz, this certainly is odd behaviour.. Can you please specify the commands you used for training and evaluation? A copy of your config file would also be helpfull

**Comment by turowicz** [comment]
More details here:

https://github.com/tensorflow/models/issues/9229#event-3761398431

**Comment by turowicz** [comment]
@sglvladi that was EfficientNet
