### ISSUE TITLE
Regarding UnicodeDecodeError

### ISSUE THREAD

**Issue by jung-sang** [sglvladi/TensorFlowObjectDetectionTutorial#51]
im having an UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 132: invalid start byte on generate_tfrecord.py

would you help me sort it out ?

the error is like below :

(tf2) C:\Users\User\Documents\Tensorflow\scripts\preprocessing>python generate_tfrecord.py -x C:/Users/User/Documents/Tensorflow/workspace/training_demo/images/train -l C:/Users/User/Documents/Tensorflow/workspace/training_demo/annotations/label_map.pbtxt -o C:/Users/User/Documents/Tensorflow/workspace/training_demo/annotations/train.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 61, in <module>
    label_map = label_map_util.load_labelmap(args.labels_path)
  File "C:\Users\User\Documents\Tensorflow\models\research\object_detection\utils\label_map_util.py", line 156, in load_labelmap
    label_map_string = fid.read()
  File "C:\Users\User\anaconda3\envs\tf2\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
    self._preread_check()
  File "C:\Users\User\anaconda3\envs\tf2\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 78, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 132: invalid start byte

**Comment by jung-sang** [comment]
sorry i sorted it out on my own, the problem was the path on your tutorial was wrong

**Comment by sglvladi** [comment]
> sorry i sorted it out on my own, the problem was the path on your tutorial was wrong

@jung-sang Can you please specify which part of the path was wrong?

**Comment by jung-sang** [comment]
your path on tutorial were okay, but it didnt work on my computer, so i had to designate the path specifically

thank you very much for all your works !

**Comment by rnrllah07** [comment]
> öğreticideki yolunuz iyiydi, ancak bilgisayarımda işe yaramadı, bu yüzden yolu özellikle belirtmek zorunda kaldım
> 
> tüm çalışmalarınız için çok teşekkür ederim!

İ have error when training part. Not generate tfrecord part. But this error can be relation with my error. How do you solve problem.? Which part you edit from original
