### ISSUE TITLE
TFOD2 How to export model based on arbitrary checkpoint instead of latest checkpoint

### ISSUE THREAD

**Issue by khengkok** [sglvladi/TensorFlowObjectDetectionTutorial#57]
In the previous version of TFOD, the export inference graph function allows us to specify which particular checkpoint to export. However, in this new version, the exporter_main_v2.py only takes in parameter training_checkpoint_dir and looking at the source code, it seems that that it only takes in the latest checkpoint.  

My workaround for this is to check the file checkpoint to reflect the different checkpoint filename, instead of the latest one. I am hoping if there is a better way to do this.

**Comment by sglvladi** [comment]
@khengkok I am afraid I have not tried this, but you are right; it would be convenient to export from previous checkpoints. Thus, I would suggest that you redirect your question to either [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) or to the [Tensorflow Models repo](https://github.com/tensorflow/models), as advised by [Tensorflow](https://www.tensorflow.org/community/) themselves.
