### ISSUE TITLE
Automate label_map and config file creation

### ISSUE THREAD

**Issue by yasserius** [sglvladi/TensorFlowObjectDetectionTutorial#58]
Hi,

Thank you to all the creators for this awesome tutorial, with in-depth description of every step.

However, I have been implementing the steps in [colab](https://colab.research.google.com/drive/1dQDCmRG28QBHDWoD3OsvUBzjSbhAuPnz?usp=sharing) and found a really [awesome notebook from google](https://colab.research.google.com/github/cloud-annotations/google-colab-training/blob/master/object_detection.ipynb), which automates a lot of the things like creation of `label_map.pbtxt` and `pipeline.config`, and user mainly has to input the images and xml files in PASCAL VOC format, along with pretrained model link from model zoo. However, that colab is outdated and uses TF1.

I already have used the techniques in those colabs and tried to automate a lot of the process in this [colab](https://colab.research.google.com/drive/1kIulJMjJ-9pBVVBFhXE1niXpkegy68yl?usp=sharing), but it is still not perfect and has bugs and is brittle.

But I would love to complete that colab and send a pull request here, if you are interested in a colab version of the tutorial.

Thanks for reading! I await your reply.

**Comment by sglvladi** [comment]
@yasserius thanks for your interest. Certainly automating the creation of the `label_map.pbtxt` and `.config` files sound interesting. Any contribution to the tutorial is more that welcome! 

Since you mentioned colab, there is [a nice TF2 colab tutorial](https://medium.com/swlh/tensorflow-2-object-detection-api-with-google-colab-b2af171e81cc) produced recently by Nisarg Kapkar, which makes use of some of the content in this tutorial and might be of interest.

**Comment by yasserius** [comment]
@sglvladi Thank you for getting back to me. I apologize for the late reply, I was inactive on github.

I read through Nisarg Kapkar's article, and he is still using the manual process.

I managed to make the colab work, along with automatic `pipeline.config` and `label_map.pbtxt` creation. Here is the draft [colab](https://colab.research.google.com/drive/1Dn3bgYkialkPXImM1XWaYqjgVNTGI9Fn?usp=sharing).

I would love your feedback on the colab. While I did not write the last steps yet (model export), it will be helpful to me if you let me know which parts can be improved. Also, it would be great if you could run the colab yourself and try to find bugs.

Thank you for your time.
