### ISSUE TITLE
NameError: name 'label_map_util' is not defined

### ISSUE THREAD

**Issue by mkdthanga** [sglvladi/TensorFlowObjectDetectionTutorial#6]
Hello everyone,
I am new to python and learning Object detection with Tensorflow Library using my Laptop Webcam.
I can't run this webcam detection program successfully. On line 14, it shows a Name error! And where should I run this TensorFlowObjectDetectionTutorial
/ webcam Program? Either in Pycharm or Anaconda? I have followed all the setup/Installation instructions from your documentation
ERROR:
Traceback (most recent call last):
  File "C:/Users/mkdth/PycharmProjects/test1/Webcam_tensorflow.py", line 56, in <module>
    label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
NameError: name 'label_map_util' is not defined
[ WARN:0] terminating async callback

Please help me out.

Thanks in advance!

**Comment by sglvladi** [comment]
@mkdthanga Have you made sure all imports are performed correctly?

More specifically, it looks like you may have missed the following:

```python
from utils import label_map_util
```

Try adding the above line to your imports and hopefully this should resolve your issue.

**Comment by sglvladi** [comment]
Closing as there has been no correspondence in 1.5 months. Feel free to re-open if necessary.
