### ISSUE TITLE
Possibility of trying this generate_tfrecord.py in colab

### ISSUE THREAD

**Issue by EziamaUgonna** [sglvladi/TensorFlowObjectDetectionTutorial#68]
I tried using this generate_tfrecord.py in Google  Colab and it is throwing some errors. Is there anyway I can modify the code to accommodate being used in  IPython notebook?

**Comment by bimmui** [comment]
If you're trying to create .tfrecord files from what I assume is your .xml files, I suggest using [https://app.roboflow.com/](https://app.roboflow.com/). I was stuck with the `generate_tfrecord.py` script with Google Colab too so I just decided to use an online solution to help me out with that particular part. 

If Roboflow doesn't work out, there are probably other online solutions out there if you look hard enough.

**Comment by EziamaUgonna** [comment]
Thanks for the information

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
