### ISSUE TITLE
Convert .xml to .record script doesn't do anything

### ISSUE THREAD

**Issue by cd11one** [sglvladi/TensorFlowObjectDetectionTutorial#73]
The script for converting the .xml files created with labelImg to .record files from your tutorial doesn't do anything for me.
I added the required arguments -x, -l, -o but didn't get any response. 
There was neither an error nor any output at all.
Since i am still an absolute beginner it could be me forgetting something, but i just can't figure out what the problem is.

**Comment by bfhaha** [comment]
It should print out the following message:
```Successfully created the TFRecord file: dataset/train/train.record```
My environment is Google Colab and used the command
```!python3 dataset/train/generate_tfrecord.py -x dataset/train -l dataset/train/label_map.pbtxt -o dataset/train/train.record```
I have the following file structure:
dataset
+--train
      +--img_1.jpg
      +--img_1.xml
      +--label_map.pbtxt
      +--generate_tfrecord.py
+--test
      +--img_2.jpg
      +--img_2.xml
      +--label_map.pbtxt
      +--generate_tfrecord.py
