### ISSUE TITLE
failed building wheels for pycocotools

### ISSUE THREAD

**Issue by mywebdesign-hub** [sglvladi/TensorFlowObjectDetectionTutorial#78]
im unable to install pycocotools in windows. I had already installed Microsoft visual c++ build tools. I have almost searched the google for this issue but couldn't install it till now. Also installed python-dev tools. Tried doing locally on cmd and also cloned the repository of cocopi from GitHub. Nothing seems to be working. What do i do now?

**Comment by sglvladi** [comment]
@kutsrfikh Have your tried installing pycocotools as documented in respective section of the tutorial (see [here](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#coco-api-installation))? 

If so, what errors are you encountering?
