### ISSUE TITLE
Tensorflow versions out of sync

### ISSUE THREAD

**Issue by kalpit-konverge** [sglvladi/TensorFlowObjectDetectionTutorial#80]
Hi,

In the TensorFlow Installation, the document specifies tf 2.2.0
`pip install --ignore-installed --upgrade tensorflow==2.2.0`

whereas when installing tf-models-official, tf >=2.5.0 is required and installed. This creates unnecessary installation overhead.

**Comment by sglvladi** [comment]
@kalpit-konverge The tutorial has now been updated for Tensorflow 2.5.0. See [here](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/).

Please note that different CUDA Toolkit and CuDNN versions apply.
