### ISSUE TITLE
pip install stuck in finding correct packages, lots of backtracing

### ISSUE THREAD

**Issue by scintillahx** [sglvladi/TensorFlowObjectDetectionTutorial#83]
I followed the exact steps in the tutorial, got everything (including Tensorflow GPU) except stuck at the last step. 

Python: 3.9.6
Pip: 21.1.3
Tensorflow: 2.5.0

Here is the output: 

WARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.
Processing c:\users\e173615\documents\project\defect_classification\tensorflow\models\research
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: avro-python3 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\avro_python3-1.10.2-py3.9.egg (from object-detection==0.1) (1.10.2)
Requirement already satisfied: apache-beam in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\apache_beam-2.31.0-py3.9-win-amd64.egg (from object-detection==0.1) (2.31.0)
Requirement already satisfied: pillow in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\pillow-8.3.1-py3.9-win-amd64.egg (from object-detection==0.1) (8.3.1)
Requirement already satisfied: lxml in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\lxml-4.6.3-py3.9-win-amd64.egg (from object-detection==0.1) (4.6.3)
Requirement already satisfied: matplotlib in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\matplotlib-3.4.2-py3.9-win-amd64.egg (from object-detection==0.1) (3.4.2)
Requirement already satisfied: Cython in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from object-detection==0.1) (0.29.24)
Requirement already satisfied: contextlib2 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\contextlib2-21.6.0-py3.9.egg (from object-detection==0.1) (21.6.0)
Requirement already satisfied: tf-slim in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\tf_slim-1.1.0-py3.9.egg (from object-detection==0.1) (1.1.0)
Requirement already satisfied: six in c:\users\e173615\appdata\roaming\python\python39\site-packages (from object-detection==0.1) (1.15.0)
Requirement already satisfied: pycocotools in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from object-detection==0.1) (2.0)
Requirement already satisfied: lvis in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\lvis-0.5.3-py3.9.egg (from object-detection==0.1) (0.5.3)
Requirement already satisfied: scipy in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\scipy-1.7.0-py3.9-win-amd64.egg (from object-detection==0.1) (1.7.0)
Requirement already satisfied: pandas in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\pandas-1.3.0-py3.9-win-amd64.egg (from object-detection==0.1) (1.3.0)
Requirement already satisfied: tf-models-official in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\tf_models_official-2.5.0-py3.9.egg (from object-detection==0.1) (2.5.0)
Collecting avro-python3
  Using cached avro_python3-1.9.2.1-py3-none-any.whl
Requirement already satisfied: crcmod<2.0,>=1.7 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\crcmod-1.7-py3.9-win-amd64.egg (from apache-beam->object-detection==0.1) (1.7)
Requirement already satisfied: dill<0.3.2,>=0.3.1.1 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\dill-0.3.1.1-py3.9.egg (from apache-beam->object-detection==0.1) (0.3.1.1)
Requirement already satisfied: fastavro<2,>=0.21.4 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\fastavro-1.4.2-py3.9-win-amd64.egg (from apache-beam->object-detection==0.1) (1.4.2)
Requirement already satisfied: future<1.0.0,>=0.18.2 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\future-0.18.2-py3.9.egg (from apache-beam->object-detection==0.1) (0.18.2)
Requirement already satisfied: grpcio<2,>=1.29.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from apache-beam->object-detection==0.1) (1.34.1)
Requirement already satisfied: hdfs<3.0.0,>=2.1.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\hdfs-2.6.0-py3.9.egg (from apache-beam->object-detection==0.1) (2.6.0)
Requirement already satisfied: httplib2<0.20.0,>=0.8 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\httplib2-0.19.1-py3.9.egg (from apache-beam->object-detection==0.1) (0.19.1)
Requirement already satisfied: numpy<1.21.0,>=1.14.3 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from apache-beam->object-detection==0.1) (1.19.5)
Requirement already satisfied: pymongo<4.0.0,>=3.8.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\pymongo-3.12.0-py3.9-win-amd64.egg (from apache-beam->object-detection==0.1) (3.12.0)
Requirement already satisfied: oauth2client<5,>=2.0.1 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\oauth2client-4.1.3-py3.9.egg (from apache-beam->object-detection==0.1) (4.1.3)
Requirement already satisfied: protobuf<4,>=3.12.2 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from apache-beam->object-detection==0.1) (3.17.3)
Requirement already satisfied: pyarrow<5.0.0,>=0.15.1 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\pyarrow-4.0.1-py3.9-win-amd64.egg (from apache-beam->object-detection==0.1) (4.0.1)
Requirement already satisfied: pydot<2,>=1.2.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\pydot-1.4.2-py3.9.egg (from apache-beam->object-detection==0.1) (1.4.2)
Requirement already satisfied: python-dateutil<3,>=2.8.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\python_dateutil-2.8.2-py3.9.egg (from apache-beam->object-detection==0.1) (2.8.2)
Requirement already satisfied: pytz>=2018.3 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\pytz-2021.1-py3.9.egg (from apache-beam->object-detection==0.1) (2021.1)
Requirement already satisfied: requests<3.0.0,>=2.24.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from apache-beam->object-detection==0.1) (2.26.0)
Requirement already satisfied: typing-extensions<3.8.0,>=3.7.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from apache-beam->object-detection==0.1) (3.7.4.3)
Requirement already satisfied: docopt in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from hdfs<3.0.0,>=2.1.0->apache-beam->object-detection==0.1) (0.6.2)
Collecting pyparsing<3,>=2.4.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Requirement already satisfied: pyasn1-modules>=0.0.5 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from oauth2client<5,>=2.0.1->apache-beam->object-detection==0.1) (0.2.8)
Requirement already satisfied: pyasn1>=0.1.7 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from oauth2client<5,>=2.0.1->apache-beam->object-detection==0.1) (0.4.8)
Requirement already satisfied: rsa>=3.1.4 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from oauth2client<5,>=2.0.1->apache-beam->object-detection==0.1) (4.7.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from requests<3.0.0,>=2.24.0->apache-beam->object-detection==0.1) (2.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from requests<3.0.0,>=2.24.0->apache-beam->object-detection==0.1) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from requests<3.0.0,>=2.24.0->apache-beam->object-detection==0.1) (2021.5.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from requests<3.0.0,>=2.24.0->apache-beam->object-detection==0.1) (1.26.6)
Requirement already satisfied: cycler>=0.10.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\cycler-0.10.0-py3.9.egg (from lvis->object-detection==0.1) (0.10.0)
Requirement already satisfied: kiwisolver>=1.1.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\kiwisolver-1.3.1-py3.9-win-amd64.egg (from lvis->object-detection==0.1) (1.3.1)
Requirement already satisfied: opencv-python>=4.1.0.25 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\opencv_python-4.5.3.56-py3.9-win-amd64.egg (from lvis->object-detection==0.1) (4.5.3.56)
Requirement already satisfied: gin-config in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\gin_config-0.4.0-py3.9.egg (from tf-models-official->object-detection==0.1) (0.4.0)
Requirement already satisfied: google-api-python-client>=1.6.7 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\google_api_python_client-2.13.0-py3.9.egg (from tf-models-official->object-detection==0.1) (2.13.0)
Requirement already satisfied: google-cloud-bigquery>=0.31.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\google_cloud_bigquery-2.21.0-py3.9.egg (from tf-models-official->object-detection==0.1) (2.21.0)
Requirement already satisfied: kaggle>=1.3.9 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\kaggle-1.5.12-py3.9.egg (from tf-models-official->object-detection==0.1) (1.5.12)
Requirement already satisfied: opencv-python-headless in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\opencv_python_headless-4.5.3.56-py3.9-win-amd64.egg (from tf-models-official->object-detection==0.1) (4.5.3.56)
Requirement already satisfied: psutil>=5.4.3 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\psutil-5.8.0-py3.9-win-amd64.egg (from tf-models-official->object-detection==0.1) (5.8.0)
Requirement already satisfied: py-cpuinfo>=3.3.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\py_cpuinfo-8.0.0-py3.9.egg (from tf-models-official->object-detection==0.1) (8.0.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\pyyaml-5.4.1-py3.9-win-amd64.egg (from tf-models-official->object-detection==0.1) (5.4.1)
Requirement already satisfied: sacrebleu in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\sacrebleu-1.5.1-py3.9.egg (from tf-models-official->object-detection==0.1) (1.5.1)
Requirement already satisfied: sentencepiece in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\sentencepiece-0.1.96-py3.9-win-amd64.egg (from tf-models-official->object-detection==0.1) (0.1.96)
Requirement already satisfied: seqeval in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\seqeval-1.2.2-py3.9.egg (from tf-models-official->object-detection==0.1) (1.2.2)
Requirement already satisfied: tensorflow-addons in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\tensorflow_addons-0.13.0-py3.9-win-amd64.egg (from tf-models-official->object-detection==0.1) (0.13.0)
Requirement already satisfied: tensorflow-datasets in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\tensorflow_datasets-4.3.0-py3.9.egg (from tf-models-official->object-detection==0.1) (4.3.0)
Requirement already satisfied: tensorflow-hub>=0.6.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\tensorflow_hub-0.12.0-py3.9.egg (from tf-models-official->object-detection==0.1) (0.12.0)
Requirement already satisfied: tensorflow-model-optimization>=0.4.1 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages\tensorflow_model_optimization-0.6.0-py3.9.egg (from tf-models-official->object-detection==0.1) (0.6.0)
Requirement already satisfied: tensorflow>=2.5.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from tf-models-official->object-detection==0.1) (2.5.0)
Requirement already satisfied: google-api-core<2dev,>=1.21.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from google-api-python-client>=1.6.7->tf-models-official->object-detection==0.1) (1.31.0)
Requirement already satisfied: google-auth-httplib2>=0.1.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from google-api-python-client>=1.6.7->tf-models-official->object-detection==0.1) (0.1.0)
Requirement already satisfied: google-auth<2dev,>=1.16.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from google-api-python-client>=1.6.7->tf-models-official->object-detection==0.1) (1.32.1)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from google-api-python-client>=1.6.7->tf-models-official->object-detection==0.1) (3.0.1)
Requirement already satisfied: setuptools>=40.3.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client>=1.6.7->tf-models-official->object-detection==0.1) (57.1.0)
Requirement already satisfied: packaging>=14.3 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client>=1.6.7->tf-models-official->object-detection==0.1) (21.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client>=1.6.7->tf-models-official->object-detection==0.1) (1.53.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client>=1.6.7->tf-models-official->object-detection==0.1) (4.2.2)
Requirement already satisfied: google-cloud-core<2.0dev,>=1.4.1 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from google-cloud-bigquery>=0.31.0->tf-models-official->object-detection==0.1) (1.7.1)
Requirement already satisfied: google-resumable-media<2.0dev,>=0.6.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from google-cloud-bigquery>=0.31.0->tf-models-official->object-detection==0.1) (1.3.1)
Collecting grpcio<2,>=1.29.0
  Using cached grpcio-1.38.1-cp39-cp39-win_amd64.whl (3.2 MB)
Requirement already satisfied: proto-plus>=1.10.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from google-cloud-bigquery>=0.31.0->tf-models-official->object-detection==0.1) (1.19.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery>=0.31.0->tf-models-official->object-detection==0.1) (1.1.2)
Requirement already satisfied: cffi>=1.0.0 in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery>=0.31.0->tf-models-official->object-detection==0.1) (1.14.6)
Requirement already satisfied: pycparser in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery>=0.31.0->tf-models-official->object-detection==0.1) (2.20)
Requirement already satisfied: tqdm in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from kaggle>=1.3.9->tf-models-official->object-detection==0.1) (4.61.2)
Requirement already satisfied: python-slugify in c:\users\e173615\anaconda3\envs\tfobj39\lib\site-packages (from kaggle>=1.3.9->tf-models-official->object-detection==0.1) (5.0.2)
Requirement already satisfied: wrapt~=1.12.1 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from tensorflow>=2.5.0->tf-models-official->object-detection==0.1) (1.12.1)
Requirement already satisfied: keras-nightly~=2.5.0.dev in c:\users\e173615\appdata\roaming\python\python39\site-packages (from tensorflow>=2.5.0->tf-models-official->object-detection==0.1) (2.5.0.dev2021032900)
Requirement already satisfied: flatbuffers~=1.12.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from tensorflow>=2.5.0->tf-models-official->object-detection==0.1) (1.12)
Requirement already satisfied: opt-einsum~=3.3.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from tensorflow>=2.5.0->tf-models-official->object-detection==0.1) (3.3.0)
Requirement already satisfied: tensorboard~=2.5 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from tensorflow>=2.5.0->tf-models-official->object-detection==0.1) (2.5.0)
Requirement already satisfied: absl-py~=0.10 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from tensorflow>=2.5.0->tf-models-official->object-detection==0.1) (0.13.0)
Requirement already satisfied: keras-preprocessing~=1.1.2 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from tensorflow>=2.5.0->tf-models-official->object-detection==0.1) (1.1.2)
Requirement already satisfied: termcolor~=1.1.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from tensorflow>=2.5.0->tf-models-official->object-detection==0.1) (1.1.0)
Requirement already satisfied: h5py~=3.1.0 in c:\users\e173615\appdata\roaming\python\python39\site-packages (from tensorflow>=2.5.0->tf-models-official->object-detection==0.1) (3.1.0)
INFO: pip is looking at multiple versions of pyyaml to determine which version is compatible with other requirements. This could take a while.
Collecting pyyaml>=5.1
  Using cached PyYAML-5.4.1-cp39-cp39-win_amd64.whl (213 kB)
  Using cached PyYAML-5.4-cp39-cp39-win_amd64.whl (213 kB)
  Using cached PyYAML-5.3.1-cp39-cp39-win_amd64.whl (212 kB)
  Using cached PyYAML-5.3.tar.gz (268 kB)
  Using cached PyYAML-5.2.tar.gz (265 kB)
  Using cached PyYAML-5.1.2.tar.gz (265 kB)
  Using cached PyYAML-5.1.1.tar.gz (274 kB)
INFO: pip is looking at multiple versions of pyyaml to determine which version is compatible with other requirements. This could take a while.
  Using cached PyYAML-5.1.tar.gz (274 kB)
INFO: pip is looking at multiple versions of py-cpuinfo to determine which version is compatible with other requirements. This could take a while.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/py-cpuinfo/
Collecting py-cpuinfo>=3.3.0
  Using cached py_cpuinfo-8.0.0-py3-none-any.whl
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached py-cpuinfo-7.0.0.tar.gz (95 kB)
  Using cached py-cpuinfo-6.0.0.tar.gz (145 kB)
  Using cached py-cpuinfo-5.0.0.tar.gz (82 kB)
  Using cached py-cpuinfo-4.0.0.tar.gz (79 kB)
  Using cached py-cpuinfo-3.3.0.tar.gz (76 kB)
INFO: pip is looking at multiple versions of psutil to determine which version is compatible with other requirements. This could take a while.
Collecting psutil>=5.4.3
  Using cached psutil-5.8.0-cp39-cp39-win_amd64.whl (246 kB)
INFO: pip is looking at multiple versions of py-cpuinfo to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached psutil-5.7.3.tar.gz (465 kB)
  Using cached psutil-5.7.2.tar.gz (460 kB)
  Using cached psutil-5.7.1.tar.gz (460 kB)
  Using cached psutil-5.7.0.tar.gz (449 kB)
  Using cached psutil-5.6.7.tar.gz (448 kB)
  Using cached psutil-5.6.6.tar.gz (447 kB)
INFO: pip is looking at multiple versions of psutil to determine which version is compatible with other requirements. This could take a while.
  Using cached psutil-5.6.5.tar.gz (447 kB)
  Using cached psutil-5.6.4.tar.gz (447 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Using cached psutil-5.6.3.tar.gz (435 kB)
  Using cached psutil-5.6.2.tar.gz (432 kB)
  Using cached psutil-5.6.1.tar.gz (427 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached psutil-5.6.0.tar.gz (426 kB)
  Using cached psutil-5.5.1.tar.gz (426 kB)
  Using cached psutil-5.5.0.tar.gz (425 kB)
  Using cached psutil-5.4.8.tar.gz (422 kB)
  Using cached psutil-5.4.7.tar.gz (420 kB)
  Using cached psutil-5.4.6.tar.gz (418 kB)
  Using cached psutil-5.4.5.tar.gz (418 kB)
  Using cached psutil-5.4.4.tar.gz (417 kB)
  Using cached psutil-5.4.3.tar.gz (412 kB)
INFO: pip is looking at multiple versions of proto-plus to determine which version is compatible with other requirements. This could take a while.
Collecting proto-plus>=1.10.0
  Using cached proto_plus-1.19.0-py3-none-any.whl (42 kB)

This process is stuck for awhile without any movement.

**Comment by scintillahx** [comment]
Problem solved by downgrading pip version to 20.2

**Comment by kaylebg** [comment]
While I know this issue is closed, I wonder if it would be worth just updating the documentation to include that the pip version requirement is 20.2. 2020-resolver is no longer supported on newer pip versions and it's easy enough to just make sure the pip version requirement is made apparent so issues can be avoided. Just food for thought!
