### ISSUE TITLE
TensorFlow 2 version used a TensorFlow 1 version code

### ISSUE THREAD

**Issue by bfhaha** [sglvladi/TensorFlowObjectDetectionTutorial#94]
I am reading this tutorial: TensorFlow 2 Object Detection API tutorial. In this script, 
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/2.2.0/training.html#convert-xml-to-record
there is a line
```import tensorflow.compat.v1 as tf```
Which causes an error AttributeError: module 'tensorflow' has no attribute 'gfile'
Does anyone know how to solve it? Thanks.

**Comment by jonthierry** [comment]
import tensorflow._api.v2.compat.v1 as tf

**Comment by bfhaha** [comment]
@jonthierry It doesn't work. Thanks.

**Comment by jonthierry** [comment]
> @jonthierry It doesn't work. Thanks.

Make sure only tensorflow 2 is installed on your system/virtual environment.

**Comment by bfhaha** [comment]
@jonthierry I figured it out the problem was caused by installing a wrong version of Tensorflow Object Detection API. That is, I should use 
```!pip install tf2-tensorflow-object-detection-api```
NOT
```!pip install tensorflow-object-detection-api```
Anyway, thanks.
