### ISSUE TITLE
Installation fails for Apple M1 with Tensorflow 2.5 and Tensorflow metal

### ISSUE THREAD

**Issue by Razin-Tailor** [sglvladi/TensorFlowObjectDetectionTutorial#97]
- I followed [Tensorflow Metal Installation](https://developer.apple.com/metal/tensorflow-plugin/) and I was able to run tensorflow and train neural networks on Apple M1.
- Then I tried to install Tensorflow Object Detection API following [Installation Guidelines](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html)
- The installation fails with the following message
<img width="1341" alt="Screenshot 2021-08-30 at 5 46 46 AM" src="https://user-images.githubusercontent.com/11299270/131270170-8135a96f-8797-4f29-8c62-65fb635d8404.png">

I tried many things, but no luck as yet.

**Comment by sglvladi** [comment]
@Razin-Tailor, I'm sorry to hear you've had issues. Did you install on a clean Python environment (may that be using Anaconda or venv)?

**Comment by Razin-Tailor** [comment]
@sglvladi Sorry to respond late. As I said, I installed miniconda and followed the installation instructions on miniconda environment for tensorflow-metal installation. That worked fine. -- Then I followed the steps for installation of tensorflow-object-detection-api in the same miniconda environment.

**Comment by JakobStadlhuber** [comment]
> @sglvladi Sorry to respond late. As I said, I installed miniconda and followed the installation instructions on miniconda environment for tensorflow-metal installation. That worked fine. -- Then I followed the steps for installation of tensorflow-object-detection-api in the same miniconda environment.

did you find a solution? does it work on your mac m1?

**Comment by Razin-Tailor** [comment]
> > @sglvladi Sorry to respond late. As I said, I installed miniconda and followed the installation instructions on miniconda environment for tensorflow-metal installation. That worked fine. -- Then I followed the steps for installation of tensorflow-object-detection-api in the same miniconda environment.
> 
> did you find a solution? does it work on your mac m1?

> > @JakobStadlhuber  No. I am still stuck!

**Comment by JakobStadlhuber** [comment]
> > > @sglvladi Sorry to respond late. As I said, I installed miniconda and followed the installation instructions on miniconda environment for tensorflow-metal installation. That worked fine. -- Then I followed the steps for installation of tensorflow-object-detection-api in the same miniconda environment.
> > 
> > 
> > did you find a solution? does it work on your mac m1?
> 
> > > @JakobStadlhuber  No. I am still stuck!

Ok, but are you sure that you selected the right conda env? In your screenshot base is selected.

**Comment by vineetsharma14** [comment]
I am also not able to use Tensor Object Detection API on Apple M1. 

I am able to install Tensorflow for MacOS using the miniforge. I am unable to install Tensorflow Object Detection API.

I am using Tensorflow Object Detection API on Linux with GPUs, and also on an Intel based Mac and it works for both of them. The only issue is on Apple M1 Chip
