### ISSUE TITLE
Export command references my_efficientdet_d1 instead of my_ssd_resnet50_v1_fpn

### ISSUE THREAD

**Issue by Vlaxtocia** [sglvladi/TensorFlowObjectDetectionTutorial#98]
Following the tutorial along, we download my_ssd_resnet50_v1_fpn (although the tutorial says you can download anything), the final step of exporting tells you to run the following command:

`python .\exporter_main_v2.py --input_type image_tensor --pipeline_config_path .\models\my_efficientdet_d1\pipeline.config --trained_checkpoint_dir .\models\my_efficientdet_d1\ --output_directory .\exported-models\my_model`

But my_efficientdet_d1 hasn't been downloaded, and the tutorial doesn't make it clear that this should be substituted for the name of the pre-trained model that the user downloaded.

**Comment by sglvladi** [comment]
@Vlaxtocia Thanks for spotting this. This has now been fixed in 7fce10c
